apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: official-official.tap.example.com.0.0.0
spec:
  refName: official-official.tap.example.com
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: official-official.tap.example.com
spec:
  displayName: official-official
  longDescription: awesome things
  maintainers:
  - name: dont-email-me@example.com
  providerName: dont-email-me@example.com
  shortDescription: enrich some stuff
  supportDescription: dont-email-me@example.com

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: official-official
spec:
  packageRef:
    refName: official-official.tap.example.com
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: official-official-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
