apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageRepositoryBuild
metadata:
  creationTimestamp: null
  name: official-official-repo.tap.example.com
spec:
  export:
    imgpkgBundle:
      image: harbor-repo.vmware.com/tanzu_practice/conventions/official-official-repo-bundle
