---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: official-official-repository
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: "official-official-repository"
    kapp.k14s.io/change-rule.delete-order: "delete after deleting official-official"
    kapp.k14s.io/change-rule.create-order: "upsert before upserting official-official"
spec:
  fetch:
    imgpkgBundle:
      image: registry.harbor.learn.tapsme.org/convention-service/official-official-repo-bundle:0.1.0
      secretRef:
        name: tap-registry
        namespace: tap-install